server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Make React Router work by serving index.html for all matching requests
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional optimizations
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webm)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
